export type RecipeUrl = {
  url: string
  source: 'nyt' | 'ba' | 'recdex'
  category: string
}

export const RECIPE_URLS: RecipeUrl[] = [
  // ============================================================
  // NYT COOKING (~250 recipes)
  // ============================================================

  // --- American Classics (~40) ---
  { url: 'https://cooking.nytimes.com/recipes/1022733-smash-burgers', source: 'nyt', category: 'American' },
  { url: 'https://cooking.nytimes.com/recipes/1017518-classic-meatloaf', source: 'nyt', category: 'American' },
  { url: 'https://cooking.nytimes.com/recipes/1015819-creamy-macaroni-and-cheese', source: 'nyt', category: 'American' },
  { url: 'https://cooking.nytimes.com/recipes/1018219-buttermilk-fried-chicken', source: 'nyt', category: 'American' },
  { url: 'https://cooking.nytimes.com/recipes/1017457-classic-pot-roast', source: 'nyt', category: 'American' },
  { url: 'https://cooking.nytimes.com/recipes/1013998-perfect-mashed-potatoes', source: 'nyt', category: 'American' },
  { url: 'https://cooking.nytimes.com/recipes/1016965-southern-corn-bread', source: 'nyt', category: 'American' },
  { url: 'https://cooking.nytimes.com/recipes/1017100-texas-chili', source: 'nyt', category: 'American' },
  { url: 'https://cooking.nytimes.com/recipes/1018337-slow-cooker-pulled-pork', source: 'nyt', category: 'American' },
  { url: 'https://cooking.nytimes.com/recipes/1017062-buffalo-wings', source: 'nyt', category: 'American' },
  { url: 'https://cooking.nytimes.com/recipes/1021053-creamy-coleslaw', source: 'nyt', category: 'American' },
  { url: 'https://cooking.nytimes.com/recipes/1013741-buttermilk-biscuits', source: 'nyt', category: 'American' },
  { url: 'https://cooking.nytimes.com/recipes/1019846-perfect-grilled-cheese', source: 'nyt', category: 'American' },
  { url: 'https://cooking.nytimes.com/recipes/1021840-classic-blt', source: 'nyt', category: 'American' },
  { url: 'https://cooking.nytimes.com/recipes/1015614-classic-potato-salad', source: 'nyt', category: 'American' },
  { url: 'https://cooking.nytimes.com/recipes/1018404-deviled-eggs', source: 'nyt', category: 'American' },
  { url: 'https://cooking.nytimes.com/recipes/1019772-smoked-brisket', source: 'nyt', category: 'American' },
  { url: 'https://cooking.nytimes.com/recipes/1019550-sloppy-joes', source: 'nyt', category: 'American' },
  { url: 'https://cooking.nytimes.com/recipes/1019830-hot-dogs-with-all-the-fixings', source: 'nyt', category: 'American' },
  { url: 'https://cooking.nytimes.com/recipes/1021694-turkey-club-sandwich', source: 'nyt', category: 'American' },
  { url: 'https://cooking.nytimes.com/recipes/1018631-new-england-clam-bake', source: 'nyt', category: 'American' },
  { url: 'https://cooking.nytimes.com/recipes/1015178-chicken-pot-pie', source: 'nyt', category: 'American' },
  { url: 'https://cooking.nytimes.com/recipes/1019117-crispy-chicken-tenders', source: 'nyt', category: 'American' },
  { url: 'https://cooking.nytimes.com/recipes/1022831-nashville-hot-chicken', source: 'nyt', category: 'American' },
  { url: 'https://cooking.nytimes.com/recipes/1020648-philly-cheesesteak', source: 'nyt', category: 'American' },
  { url: 'https://cooking.nytimes.com/recipes/1017256-baby-back-ribs', source: 'nyt', category: 'American' },
  { url: 'https://cooking.nytimes.com/recipes/1014205-southern-fried-catfish', source: 'nyt', category: 'American' },
  { url: 'https://cooking.nytimes.com/recipes/1021567-salisbury-steak', source: 'nyt', category: 'American' },
  { url: 'https://cooking.nytimes.com/recipes/1019524-beef-stroganoff', source: 'nyt', category: 'American' },
  { url: 'https://cooking.nytimes.com/recipes/1019689-tuna-casserole', source: 'nyt', category: 'American' },
  { url: 'https://cooking.nytimes.com/recipes/1022108-chicken-fried-steak', source: 'nyt', category: 'American' },
  { url: 'https://cooking.nytimes.com/recipes/1015773-barbecue-chicken', source: 'nyt', category: 'American' },
  { url: 'https://cooking.nytimes.com/recipes/1022467-bacon-cheeseburger', source: 'nyt', category: 'American' },
  { url: 'https://cooking.nytimes.com/recipes/1023012-reuben-sandwich', source: 'nyt', category: 'American' },
  { url: 'https://cooking.nytimes.com/recipes/1019433-cajun-jambalaya', source: 'nyt', category: 'American' },
  { url: 'https://cooking.nytimes.com/recipes/1018183-shrimp-and-grits', source: 'nyt', category: 'American' },
  { url: 'https://cooking.nytimes.com/recipes/1022190-chicken-and-dumplings', source: 'nyt', category: 'American' },
  { url: 'https://cooking.nytimes.com/recipes/1015474-gumbo', source: 'nyt', category: 'American' },
  { url: 'https://cooking.nytimes.com/recipes/1023145-thanksgiving-turkey', source: 'nyt', category: 'American' },
  { url: 'https://cooking.nytimes.com/recipes/1018529-glazed-ham', source: 'nyt', category: 'American' },

  // --- Italian (~30) ---
  { url: 'https://cooking.nytimes.com/recipes/12965-cacio-e-pepe', source: 'nyt', category: 'Italian' },
  { url: 'https://cooking.nytimes.com/recipes/1015181-marcella-hazans-bolognese-sauce', source: 'nyt', category: 'Italian' },
  { url: 'https://cooking.nytimes.com/recipes/12954-spaghetti-carbonara', source: 'nyt', category: 'Italian' },
  { url: 'https://cooking.nytimes.com/recipes/1021165-chicken-parmesan', source: 'nyt', category: 'Italian' },
  { url: 'https://cooking.nytimes.com/recipes/1017089-lasagna', source: 'nyt', category: 'Italian' },
  { url: 'https://cooking.nytimes.com/recipes/1017004-mushroom-risotto', source: 'nyt', category: 'Italian' },
  { url: 'https://cooking.nytimes.com/recipes/1014830-ricotta-gnocchi', source: 'nyt', category: 'Italian' },
  { url: 'https://cooking.nytimes.com/recipes/1021721-pasta-al-limone', source: 'nyt', category: 'Italian' },
  { url: 'https://cooking.nytimes.com/recipes/1015417-pesto-pasta', source: 'nyt', category: 'Italian' },
  { url: 'https://cooking.nytimes.com/recipes/1017523-osso-buco', source: 'nyt', category: 'Italian' },
  { url: 'https://cooking.nytimes.com/recipes/1022002-tiramisu', source: 'nyt', category: 'Italian' },
  { url: 'https://cooking.nytimes.com/recipes/1019210-panna-cotta', source: 'nyt', category: 'Italian' },
  { url: 'https://cooking.nytimes.com/recipes/1020852-pasta-alla-vodka', source: 'nyt', category: 'Italian' },
  { url: 'https://cooking.nytimes.com/recipes/1015420-eggplant-parmesan', source: 'nyt', category: 'Italian' },
  { url: 'https://cooking.nytimes.com/recipes/1017085-marinara-sauce', source: 'nyt', category: 'Italian' },
  { url: 'https://cooking.nytimes.com/recipes/1022863-pasta-e-fagioli', source: 'nyt', category: 'Italian' },
  { url: 'https://cooking.nytimes.com/recipes/1015835-amatriciana', source: 'nyt', category: 'Italian' },
  { url: 'https://cooking.nytimes.com/recipes/1021290-pasta-aglio-e-olio', source: 'nyt', category: 'Italian' },
  { url: 'https://cooking.nytimes.com/recipes/1020830-burrata-with-tomatoes', source: 'nyt', category: 'Italian' },
  { url: 'https://cooking.nytimes.com/recipes/1019512-caprese-salad', source: 'nyt', category: 'Italian' },
  { url: 'https://cooking.nytimes.com/recipes/1022975-baked-ziti', source: 'nyt', category: 'Italian' },
  { url: 'https://cooking.nytimes.com/recipes/1019312-puttanesca', source: 'nyt', category: 'Italian' },
  { url: 'https://cooking.nytimes.com/recipes/1020760-italian-wedding-soup', source: 'nyt', category: 'Italian' },
  { url: 'https://cooking.nytimes.com/recipes/1018349-chicken-piccata', source: 'nyt', category: 'Italian' },
  { url: 'https://cooking.nytimes.com/recipes/1023210-veal-milanese', source: 'nyt', category: 'Italian' },
  { url: 'https://cooking.nytimes.com/recipes/1015184-bruschetta', source: 'nyt', category: 'Italian' },
  { url: 'https://cooking.nytimes.com/recipes/1020650-meatballs', source: 'nyt', category: 'Italian' },
  { url: 'https://cooking.nytimes.com/recipes/1019843-cannoli', source: 'nyt', category: 'Italian' },
  { url: 'https://cooking.nytimes.com/recipes/1015816-cioppino', source: 'nyt', category: 'Italian' },
  { url: 'https://cooking.nytimes.com/recipes/1019602-minestrone', source: 'nyt', category: 'Italian' },

  // --- Asian (~30) ---
  { url: 'https://cooking.nytimes.com/recipes/1017358-kung-pao-chicken', source: 'nyt', category: 'Asian' },
  { url: 'https://cooking.nytimes.com/recipes/1012545-pad-thai', source: 'nyt', category: 'Asian' },
  { url: 'https://cooking.nytimes.com/recipes/1017626-egg-fried-rice', source: 'nyt', category: 'Asian' },
  { url: 'https://cooking.nytimes.com/recipes/1022011-shoyu-ramen', source: 'nyt', category: 'Asian' },
  { url: 'https://cooking.nytimes.com/recipes/1020194-pork-dumplings', source: 'nyt', category: 'Asian' },
  { url: 'https://cooking.nytimes.com/recipes/1017541-chicken-stir-fry', source: 'nyt', category: 'Asian' },
  { url: 'https://cooking.nytimes.com/recipes/1019444-teriyaki-chicken', source: 'nyt', category: 'Asian' },
  { url: 'https://cooking.nytimes.com/recipes/1018567-bibimbap', source: 'nyt', category: 'Asian' },
  { url: 'https://cooking.nytimes.com/recipes/1017153-pho', source: 'nyt', category: 'Asian' },
  { url: 'https://cooking.nytimes.com/recipes/1020638-dan-dan-noodles', source: 'nyt', category: 'Asian' },
  { url: 'https://cooking.nytimes.com/recipes/1017358-mapo-tofu', source: 'nyt', category: 'Asian' },
  { url: 'https://cooking.nytimes.com/recipes/1018309-general-tsos-chicken', source: 'nyt', category: 'Asian' },
  { url: 'https://cooking.nytimes.com/recipes/1016756-orange-chicken', source: 'nyt', category: 'Asian' },
  { url: 'https://cooking.nytimes.com/recipes/1014523-sesame-noodles', source: 'nyt', category: 'Asian' },
  { url: 'https://cooking.nytimes.com/recipes/1019675-thai-green-curry', source: 'nyt', category: 'Asian' },
  { url: 'https://cooking.nytimes.com/recipes/1020942-tonkatsu', source: 'nyt', category: 'Asian' },
  { url: 'https://cooking.nytimes.com/recipes/1018083-miso-soup', source: 'nyt', category: 'Asian' },
  { url: 'https://cooking.nytimes.com/recipes/1021534-japanese-curry', source: 'nyt', category: 'Asian' },
  { url: 'https://cooking.nytimes.com/recipes/1020193-scallion-pancakes', source: 'nyt', category: 'Asian' },
  { url: 'https://cooking.nytimes.com/recipes/1017342-char-siu-pork', source: 'nyt', category: 'Asian' },
  { url: 'https://cooking.nytimes.com/recipes/1021788-korean-fried-chicken', source: 'nyt', category: 'Asian' },
  { url: 'https://cooking.nytimes.com/recipes/1020451-sushi-rice', source: 'nyt', category: 'Asian' },
  { url: 'https://cooking.nytimes.com/recipes/1019877-tom-yum-soup', source: 'nyt', category: 'Asian' },
  { url: 'https://cooking.nytimes.com/recipes/1022430-japchae', source: 'nyt', category: 'Asian' },
  { url: 'https://cooking.nytimes.com/recipes/1019630-spring-rolls', source: 'nyt', category: 'Asian' },
  { url: 'https://cooking.nytimes.com/recipes/1022143-katsu-curry', source: 'nyt', category: 'Asian' },
  { url: 'https://cooking.nytimes.com/recipes/1020837-lo-mein', source: 'nyt', category: 'Asian' },
  { url: 'https://cooking.nytimes.com/recipes/1021934-kimchi-jjigae', source: 'nyt', category: 'Asian' },
  { url: 'https://cooking.nytimes.com/recipes/1018234-thai-basil-chicken', source: 'nyt', category: 'Asian' },
  { url: 'https://cooking.nytimes.com/recipes/1019556-wonton-soup', source: 'nyt', category: 'Asian' },

  // --- Mexican/Latin (~20) ---
  { url: 'https://cooking.nytimes.com/recipes/1020453-tacos-al-pastor', source: 'nyt', category: 'Mexican' },
  { url: 'https://cooking.nytimes.com/recipes/1018291-carnitas', source: 'nyt', category: 'Mexican' },
  { url: 'https://cooking.nytimes.com/recipes/1019247-chicken-enchiladas', source: 'nyt', category: 'Mexican' },
  { url: 'https://cooking.nytimes.com/recipes/1015494-guacamole', source: 'nyt', category: 'Mexican' },
  { url: 'https://cooking.nytimes.com/recipes/1020572-elote', source: 'nyt', category: 'Mexican' },
  { url: 'https://cooking.nytimes.com/recipes/1021329-churros', source: 'nyt', category: 'Mexican' },
  { url: 'https://cooking.nytimes.com/recipes/1016038-black-beans', source: 'nyt', category: 'Mexican' },
  { url: 'https://cooking.nytimes.com/recipes/1017612-mexican-rice', source: 'nyt', category: 'Mexican' },
  { url: 'https://cooking.nytimes.com/recipes/1020811-birria-tacos', source: 'nyt', category: 'Mexican' },
  { url: 'https://cooking.nytimes.com/recipes/1020936-chile-rellenos', source: 'nyt', category: 'Mexican' },
  { url: 'https://cooking.nytimes.com/recipes/1018720-pico-de-gallo', source: 'nyt', category: 'Mexican' },
  { url: 'https://cooking.nytimes.com/recipes/1019678-chicken-tortilla-soup', source: 'nyt', category: 'Mexican' },
  { url: 'https://cooking.nytimes.com/recipes/1021456-chilaquiles', source: 'nyt', category: 'Mexican' },
  { url: 'https://cooking.nytimes.com/recipes/1019834-tamales', source: 'nyt', category: 'Mexican' },
  { url: 'https://cooking.nytimes.com/recipes/1022356-carne-asada', source: 'nyt', category: 'Mexican' },
  { url: 'https://cooking.nytimes.com/recipes/1017891-pozole-rojo', source: 'nyt', category: 'Mexican' },
  { url: 'https://cooking.nytimes.com/recipes/1023089-mole-negro', source: 'nyt', category: 'Mexican' },
  { url: 'https://cooking.nytimes.com/recipes/1019234-refried-beans', source: 'nyt', category: 'Mexican' },
  { url: 'https://cooking.nytimes.com/recipes/1020112-chicken-quesadillas', source: 'nyt', category: 'Mexican' },
  { url: 'https://cooking.nytimes.com/recipes/1022578-empanadas', source: 'nyt', category: 'Mexican' },

  // --- Baking & Desserts (~40) ---
  { url: 'https://cooking.nytimes.com/recipes/1021334-banana-bread', source: 'nyt', category: 'Baking' },
  { url: 'https://cooking.nytimes.com/recipes/1018684-best-brownies', source: 'nyt', category: 'Baking' },
  { url: 'https://cooking.nytimes.com/recipes/1015819-chocolate-chip-cookies', source: 'nyt', category: 'Baking' },
  { url: 'https://cooking.nytimes.com/recipes/1022398-chocolate-cake', source: 'nyt', category: 'Baking' },
  { url: 'https://cooking.nytimes.com/recipes/1019363-apple-pie', source: 'nyt', category: 'Baking' },
  { url: 'https://cooking.nytimes.com/recipes/1021490-cinnamon-rolls', source: 'nyt', category: 'Baking' },
  { url: 'https://cooking.nytimes.com/recipes/1018203-no-knead-bread', source: 'nyt', category: 'Baking' },
  { url: 'https://cooking.nytimes.com/recipes/1018014-pizza-dough', source: 'nyt', category: 'Baking' },
  { url: 'https://cooking.nytimes.com/recipes/1019685-focaccia', source: 'nyt', category: 'Baking' },
  { url: 'https://cooking.nytimes.com/recipes/1018350-cream-scones', source: 'nyt', category: 'Baking' },
  { url: 'https://cooking.nytimes.com/recipes/1019311-all-butter-pie-crust', source: 'nyt', category: 'Baking' },
  { url: 'https://cooking.nytimes.com/recipes/1021378-new-york-cheesecake', source: 'nyt', category: 'Baking' },
  { url: 'https://cooking.nytimes.com/recipes/1022210-sugar-cookies', source: 'nyt', category: 'Baking' },
  { url: 'https://cooking.nytimes.com/recipes/1014853-blondies', source: 'nyt', category: 'Baking' },
  { url: 'https://cooking.nytimes.com/recipes/1021543-sourdough-bread', source: 'nyt', category: 'Baking' },
  { url: 'https://cooking.nytimes.com/recipes/1019283-lemon-bars', source: 'nyt', category: 'Baking' },
  { url: 'https://cooking.nytimes.com/recipes/1020909-carrot-cake', source: 'nyt', category: 'Baking' },
  { url: 'https://cooking.nytimes.com/recipes/1017817-pumpkin-pie', source: 'nyt', category: 'Baking' },
  { url: 'https://cooking.nytimes.com/recipes/1013711-pecan-pie', source: 'nyt', category: 'Baking' },
  { url: 'https://cooking.nytimes.com/recipes/1018245-red-velvet-cake', source: 'nyt', category: 'Baking' },
  { url: 'https://cooking.nytimes.com/recipes/1017354-challah', source: 'nyt', category: 'Baking' },
  { url: 'https://cooking.nytimes.com/recipes/1022673-croissants', source: 'nyt', category: 'Baking' },
  { url: 'https://cooking.nytimes.com/recipes/1019806-peanut-butter-cookies', source: 'nyt', category: 'Baking' },
  { url: 'https://cooking.nytimes.com/recipes/1022835-oatmeal-cookies', source: 'nyt', category: 'Baking' },
  { url: 'https://cooking.nytimes.com/recipes/1020856-snickerdoodles', source: 'nyt', category: 'Baking' },
  { url: 'https://cooking.nytimes.com/recipes/1020421-brioche', source: 'nyt', category: 'Baking' },
  { url: 'https://cooking.nytimes.com/recipes/1018371-pound-cake', source: 'nyt', category: 'Baking' },
  { url: 'https://cooking.nytimes.com/recipes/1021619-lemon-poppy-seed-muffins', source: 'nyt', category: 'Baking' },
  { url: 'https://cooking.nytimes.com/recipes/1019920-blueberry-muffins', source: 'nyt', category: 'Baking' },
  { url: 'https://cooking.nytimes.com/recipes/1022502-strawberry-shortcake', source: 'nyt', category: 'Baking' },
  { url: 'https://cooking.nytimes.com/recipes/1018735-chocolate-mousse', source: 'nyt', category: 'Baking' },
  { url: 'https://cooking.nytimes.com/recipes/1022019-creme-brulee', source: 'nyt', category: 'Baking' },
  { url: 'https://cooking.nytimes.com/recipes/1019187-peach-cobbler', source: 'nyt', category: 'Baking' },
  { url: 'https://cooking.nytimes.com/recipes/1020345-key-lime-pie', source: 'nyt', category: 'Baking' },
  { url: 'https://cooking.nytimes.com/recipes/1021783-sticky-toffee-pudding', source: 'nyt', category: 'Baking' },
  { url: 'https://cooking.nytimes.com/recipes/1018908-chocolate-lava-cake', source: 'nyt', category: 'Baking' },
  { url: 'https://cooking.nytimes.com/recipes/1023118-tres-leches-cake', source: 'nyt', category: 'Baking' },
  { url: 'https://cooking.nytimes.com/recipes/1022691-apple-crisp', source: 'nyt', category: 'Baking' },
  { url: 'https://cooking.nytimes.com/recipes/1015357-brownies-with-sea-salt', source: 'nyt', category: 'Baking' },
  { url: 'https://cooking.nytimes.com/recipes/1019453-chocolate-babka', source: 'nyt', category: 'Baking' },

  // --- Soups & Stews (~20) ---
  { url: 'https://cooking.nytimes.com/recipes/1018068-chicken-noodle-soup', source: 'nyt', category: 'Soup' },
  { url: 'https://cooking.nytimes.com/recipes/1014872-creamy-tomato-soup', source: 'nyt', category: 'Soup' },
  { url: 'https://cooking.nytimes.com/recipes/1017061-french-onion-soup', source: 'nyt', category: 'Soup' },
  { url: 'https://cooking.nytimes.com/recipes/1019183-new-england-clam-chowder', source: 'nyt', category: 'Soup' },
  { url: 'https://cooking.nytimes.com/recipes/1014756-classic-beef-stew', source: 'nyt', category: 'Soup' },
  { url: 'https://cooking.nytimes.com/recipes/1020567-red-lentil-soup', source: 'nyt', category: 'Soup' },
  { url: 'https://cooking.nytimes.com/recipes/1015319-split-pea-soup', source: 'nyt', category: 'Soup' },
  { url: 'https://cooking.nytimes.com/recipes/1019243-butternut-squash-soup', source: 'nyt', category: 'Soup' },
  { url: 'https://cooking.nytimes.com/recipes/1020343-corn-chowder', source: 'nyt', category: 'Soup' },
  { url: 'https://cooking.nytimes.com/recipes/1017912-chicken-and-rice-soup', source: 'nyt', category: 'Soup' },
  { url: 'https://cooking.nytimes.com/recipes/1019567-tortellini-soup', source: 'nyt', category: 'Soup' },
  { url: 'https://cooking.nytimes.com/recipes/1018839-gazpacho', source: 'nyt', category: 'Soup' },
  { url: 'https://cooking.nytimes.com/recipes/1020789-white-bean-soup', source: 'nyt', category: 'Soup' },
  { url: 'https://cooking.nytimes.com/recipes/1022045-broccoli-cheddar-soup', source: 'nyt', category: 'Soup' },
  { url: 'https://cooking.nytimes.com/recipes/1021289-mushroom-barley-soup', source: 'nyt', category: 'Soup' },
  { url: 'https://cooking.nytimes.com/recipes/1020023-potato-leek-soup', source: 'nyt', category: 'Soup' },
  { url: 'https://cooking.nytimes.com/recipes/1019478-matzo-ball-soup', source: 'nyt', category: 'Soup' },
  { url: 'https://cooking.nytimes.com/recipes/1022634-black-bean-soup', source: 'nyt', category: 'Soup' },
  { url: 'https://cooking.nytimes.com/recipes/1018560-ribollita', source: 'nyt', category: 'Soup' },
  { url: 'https://cooking.nytimes.com/recipes/1021076-chicken-chili-verde', source: 'nyt', category: 'Soup' },

  // --- Breakfast (~20) ---
  { url: 'https://cooking.nytimes.com/recipes/1018180-fluffy-pancakes', source: 'nyt', category: 'Breakfast' },
  { url: 'https://cooking.nytimes.com/recipes/1018261-french-toast', source: 'nyt', category: 'Breakfast' },
  { url: 'https://cooking.nytimes.com/recipes/1019735-perfect-scrambled-eggs', source: 'nyt', category: 'Breakfast' },
  { url: 'https://cooking.nytimes.com/recipes/1021063-eggs-benedict', source: 'nyt', category: 'Breakfast' },
  { url: 'https://cooking.nytimes.com/recipes/1020750-homemade-granola', source: 'nyt', category: 'Breakfast' },
  { url: 'https://cooking.nytimes.com/recipes/1020901-overnight-oats', source: 'nyt', category: 'Breakfast' },
  { url: 'https://cooking.nytimes.com/recipes/1019145-vegetable-frittata', source: 'nyt', category: 'Breakfast' },
  { url: 'https://cooking.nytimes.com/recipes/1019314-quiche-lorraine', source: 'nyt', category: 'Breakfast' },
  { url: 'https://cooking.nytimes.com/recipes/1017803-waffles', source: 'nyt', category: 'Breakfast' },
  { url: 'https://cooking.nytimes.com/recipes/1020212-shakshuka', source: 'nyt', category: 'Breakfast' },
  { url: 'https://cooking.nytimes.com/recipes/1021345-breakfast-burritos', source: 'nyt', category: 'Breakfast' },
  { url: 'https://cooking.nytimes.com/recipes/1020879-avocado-toast', source: 'nyt', category: 'Breakfast' },
  { url: 'https://cooking.nytimes.com/recipes/1019056-dutch-baby', source: 'nyt', category: 'Breakfast' },
  { url: 'https://cooking.nytimes.com/recipes/1017901-crepes', source: 'nyt', category: 'Breakfast' },
  { url: 'https://cooking.nytimes.com/recipes/1022078-egg-in-a-hole', source: 'nyt', category: 'Breakfast' },
  { url: 'https://cooking.nytimes.com/recipes/1020534-breakfast-hash', source: 'nyt', category: 'Breakfast' },
  { url: 'https://cooking.nytimes.com/recipes/1019790-chia-pudding', source: 'nyt', category: 'Breakfast' },
  { url: 'https://cooking.nytimes.com/recipes/1020167-steel-cut-oatmeal', source: 'nyt', category: 'Breakfast' },
  { url: 'https://cooking.nytimes.com/recipes/1022312-huevos-rancheros', source: 'nyt', category: 'Breakfast' },
  { url: 'https://cooking.nytimes.com/recipes/1021856-strata', source: 'nyt', category: 'Breakfast' },

  // --- Salads & Sides (~20) ---
  { url: 'https://cooking.nytimes.com/recipes/1017253-classic-caesar-salad', source: 'nyt', category: 'Salad' },
  { url: 'https://cooking.nytimes.com/recipes/1015057-greek-salad', source: 'nyt', category: 'Salad' },
  { url: 'https://cooking.nytimes.com/recipes/1018517-roasted-vegetables', source: 'nyt', category: 'Salad' },
  { url: 'https://cooking.nytimes.com/recipes/1015846-potato-gratin', source: 'nyt', category: 'Salad' },
  { url: 'https://cooking.nytimes.com/recipes/1020576-green-beans-almondine', source: 'nyt', category: 'Salad' },
  { url: 'https://cooking.nytimes.com/recipes/1019808-roasted-brussels-sprouts', source: 'nyt', category: 'Salad' },
  { url: 'https://cooking.nytimes.com/recipes/1021239-roasted-sweet-potatoes', source: 'nyt', category: 'Salad' },
  { url: 'https://cooking.nytimes.com/recipes/1013784-cobb-salad', source: 'nyt', category: 'Salad' },
  { url: 'https://cooking.nytimes.com/recipes/1018043-wedge-salad', source: 'nyt', category: 'Salad' },
  { url: 'https://cooking.nytimes.com/recipes/1020445-creamed-spinach', source: 'nyt', category: 'Salad' },
  { url: 'https://cooking.nytimes.com/recipes/1019890-glazed-carrots', source: 'nyt', category: 'Salad' },
  { url: 'https://cooking.nytimes.com/recipes/1021567-waldorf-salad', source: 'nyt', category: 'Salad' },
  { url: 'https://cooking.nytimes.com/recipes/1022783-fattoush', source: 'nyt', category: 'Salad' },
  { url: 'https://cooking.nytimes.com/recipes/1019245-hasselback-potatoes', source: 'nyt', category: 'Salad' },
  { url: 'https://cooking.nytimes.com/recipes/1020678-sauteed-mushrooms', source: 'nyt', category: 'Salad' },
  { url: 'https://cooking.nytimes.com/recipes/1018912-corn-on-the-cob', source: 'nyt', category: 'Salad' },
  { url: 'https://cooking.nytimes.com/recipes/1022189-tabbouleh', source: 'nyt', category: 'Salad' },
  { url: 'https://cooking.nytimes.com/recipes/1019334-kale-salad', source: 'nyt', category: 'Salad' },
  { url: 'https://cooking.nytimes.com/recipes/1020990-roasted-cauliflower', source: 'nyt', category: 'Salad' },
  { url: 'https://cooking.nytimes.com/recipes/1021402-panzanella', source: 'nyt', category: 'Salad' },

  // --- Seafood (~15) ---
  { url: 'https://cooking.nytimes.com/recipes/1022734-roasted-salmon', source: 'nyt', category: 'Seafood' },
  { url: 'https://cooking.nytimes.com/recipes/1018698-honey-garlic-salmon', source: 'nyt', category: 'Seafood' },
  { url: 'https://cooking.nytimes.com/recipes/1020150-shrimp-scampi', source: 'nyt', category: 'Seafood' },
  { url: 'https://cooking.nytimes.com/recipes/1020293-fish-tacos', source: 'nyt', category: 'Seafood' },
  { url: 'https://cooking.nytimes.com/recipes/1019435-crab-cakes', source: 'nyt', category: 'Seafood' },
  { url: 'https://cooking.nytimes.com/recipes/1019789-steamed-lobster', source: 'nyt', category: 'Seafood' },
  { url: 'https://cooking.nytimes.com/recipes/1018612-mussels-in-white-wine', source: 'nyt', category: 'Seafood' },
  { url: 'https://cooking.nytimes.com/recipes/1020456-seared-scallops', source: 'nyt', category: 'Seafood' },
  { url: 'https://cooking.nytimes.com/recipes/1017893-pan-roasted-halibut', source: 'nyt', category: 'Seafood' },
  { url: 'https://cooking.nytimes.com/recipes/1019067-grilled-swordfish', source: 'nyt', category: 'Seafood' },
  { url: 'https://cooking.nytimes.com/recipes/1022145-coconut-shrimp', source: 'nyt', category: 'Seafood' },
  { url: 'https://cooking.nytimes.com/recipes/1021389-blackened-catfish', source: 'nyt', category: 'Seafood' },
  { url: 'https://cooking.nytimes.com/recipes/1020678-tuna-poke', source: 'nyt', category: 'Seafood' },
  { url: 'https://cooking.nytimes.com/recipes/1018290-fish-and-chips', source: 'nyt', category: 'Seafood' },
  { url: 'https://cooking.nytimes.com/recipes/1022934-lemon-butter-cod', source: 'nyt', category: 'Seafood' },

  // --- Indian/Middle Eastern (~15) ---
  { url: 'https://cooking.nytimes.com/recipes/1019772-butter-chicken', source: 'nyt', category: 'Indian' },
  { url: 'https://cooking.nytimes.com/recipes/1019036-chicken-tikka-masala', source: 'nyt', category: 'Indian' },
  { url: 'https://cooking.nytimes.com/recipes/1018229-dal', source: 'nyt', category: 'Indian' },
  { url: 'https://cooking.nytimes.com/recipes/1015816-hummus', source: 'nyt', category: 'Indian' },
  { url: 'https://cooking.nytimes.com/recipes/1014594-falafel', source: 'nyt', category: 'Indian' },
  { url: 'https://cooking.nytimes.com/recipes/1020937-chicken-shawarma', source: 'nyt', category: 'Indian' },
  { url: 'https://cooking.nytimes.com/recipes/1019870-chicken-biryani', source: 'nyt', category: 'Indian' },
  { url: 'https://cooking.nytimes.com/recipes/1017071-naan', source: 'nyt', category: 'Indian' },
  { url: 'https://cooking.nytimes.com/recipes/1020411-chana-masala', source: 'nyt', category: 'Indian' },
  { url: 'https://cooking.nytimes.com/recipes/1019290-palak-paneer', source: 'nyt', category: 'Indian' },
  { url: 'https://cooking.nytimes.com/recipes/1021678-baba-ganoush', source: 'nyt', category: 'Indian' },
  { url: 'https://cooking.nytimes.com/recipes/1022345-lamb-kofta', source: 'nyt', category: 'Indian' },
  { url: 'https://cooking.nytimes.com/recipes/1020189-samosas', source: 'nyt', category: 'Indian' },
  { url: 'https://cooking.nytimes.com/recipes/1019654-tandoori-chicken', source: 'nyt', category: 'Indian' },
  { url: 'https://cooking.nytimes.com/recipes/1022867-lamb-kebabs', source: 'nyt', category: 'Indian' },

  // ============================================================
  // BON APPETIT (~250 recipes)
  // ============================================================

  // --- American Classics (~40) ---
  { url: 'https://www.bonappetit.com/recipe/bas-best-burger', source: 'ba', category: 'American' },
  { url: 'https://www.bonappetit.com/recipe/bas-best-fried-chicken', source: 'ba', category: 'American' },
  { url: 'https://www.bonappetit.com/recipe/classic-meatloaf', source: 'ba', category: 'American' },
  { url: 'https://www.bonappetit.com/recipe/stovetop-mac-and-cheese', source: 'ba', category: 'American' },
  { url: 'https://www.bonappetit.com/recipe/slow-roast-pulled-pork', source: 'ba', category: 'American' },
  { url: 'https://www.bonappetit.com/recipe/best-buffalo-wings', source: 'ba', category: 'American' },
  { url: 'https://www.bonappetit.com/recipe/perfect-pot-roast', source: 'ba', category: 'American' },
  { url: 'https://www.bonappetit.com/recipe/buttery-mashed-potatoes', source: 'ba', category: 'American' },
  { url: 'https://www.bonappetit.com/recipe/skillet-cornbread', source: 'ba', category: 'American' },
  { url: 'https://www.bonappetit.com/recipe/classic-chili-con-carne', source: 'ba', category: 'American' },
  { url: 'https://www.bonappetit.com/recipe/buttermilk-biscuits', source: 'ba', category: 'American' },
  { url: 'https://www.bonappetit.com/recipe/crispy-grilled-cheese', source: 'ba', category: 'American' },
  { url: 'https://www.bonappetit.com/recipe/classic-coleslaw', source: 'ba', category: 'American' },
  { url: 'https://www.bonappetit.com/recipe/perfect-deviled-eggs', source: 'ba', category: 'American' },
  { url: 'https://www.bonappetit.com/recipe/classic-potato-salad', source: 'ba', category: 'American' },
  { url: 'https://www.bonappetit.com/recipe/chicken-pot-pie', source: 'ba', category: 'American' },
  { url: 'https://www.bonappetit.com/recipe/nashville-hot-chicken-sandwich', source: 'ba', category: 'American' },
  { url: 'https://www.bonappetit.com/recipe/crispy-chicken-tenders', source: 'ba', category: 'American' },
  { url: 'https://www.bonappetit.com/recipe/smoked-brisket', source: 'ba', category: 'American' },
  { url: 'https://www.bonappetit.com/recipe/baby-back-ribs-with-barbecue-sauce', source: 'ba', category: 'American' },
  { url: 'https://www.bonappetit.com/recipe/sloppy-joes', source: 'ba', category: 'American' },
  { url: 'https://www.bonappetit.com/recipe/beef-stroganoff', source: 'ba', category: 'American' },
  { url: 'https://www.bonappetit.com/recipe/tuna-noodle-casserole', source: 'ba', category: 'American' },
  { url: 'https://www.bonappetit.com/recipe/salisbury-steak', source: 'ba', category: 'American' },
  { url: 'https://www.bonappetit.com/recipe/philly-cheesesteak', source: 'ba', category: 'American' },
  { url: 'https://www.bonappetit.com/recipe/chicken-fried-steak', source: 'ba', category: 'American' },
  { url: 'https://www.bonappetit.com/recipe/barbecue-chicken', source: 'ba', category: 'American' },
  { url: 'https://www.bonappetit.com/recipe/reuben-sandwich', source: 'ba', category: 'American' },
  { url: 'https://www.bonappetit.com/recipe/cajun-jambalaya', source: 'ba', category: 'American' },
  { url: 'https://www.bonappetit.com/recipe/shrimp-and-grits', source: 'ba', category: 'American' },
  { url: 'https://www.bonappetit.com/recipe/chicken-and-dumplings', source: 'ba', category: 'American' },
  { url: 'https://www.bonappetit.com/recipe/seafood-gumbo', source: 'ba', category: 'American' },
  { url: 'https://www.bonappetit.com/recipe/roast-turkey-with-gravy', source: 'ba', category: 'American' },
  { url: 'https://www.bonappetit.com/recipe/honey-glazed-ham', source: 'ba', category: 'American' },
  { url: 'https://www.bonappetit.com/recipe/crispy-smash-burger', source: 'ba', category: 'American' },
  { url: 'https://www.bonappetit.com/recipe/club-sandwich', source: 'ba', category: 'American' },
  { url: 'https://www.bonappetit.com/recipe/lobster-roll', source: 'ba', category: 'American' },
  { url: 'https://www.bonappetit.com/recipe/corn-dogs', source: 'ba', category: 'American' },
  { url: 'https://www.bonappetit.com/recipe/chicken-fingers', source: 'ba', category: 'American' },
  { url: 'https://www.bonappetit.com/recipe/meatball-sub', source: 'ba', category: 'American' },

  // --- Italian (~30) ---
  { url: 'https://www.bonappetit.com/recipe/cacio-e-pepe', source: 'ba', category: 'Italian' },
  { url: 'https://www.bonappetit.com/recipe/classic-bolognese', source: 'ba', category: 'Italian' },
  { url: 'https://www.bonappetit.com/recipe/spaghetti-carbonara', source: 'ba', category: 'Italian' },
  { url: 'https://www.bonappetit.com/recipe/bas-best-lasagna', source: 'ba', category: 'Italian' },
  { url: 'https://www.bonappetit.com/recipe/chicken-parmesan', source: 'ba', category: 'Italian' },
  { url: 'https://www.bonappetit.com/recipe/mushroom-risotto', source: 'ba', category: 'Italian' },
  { url: 'https://www.bonappetit.com/recipe/pasta-al-limone', source: 'ba', category: 'Italian' },
  { url: 'https://www.bonappetit.com/recipe/pasta-alla-vodka', source: 'ba', category: 'Italian' },
  { url: 'https://www.bonappetit.com/recipe/ricotta-gnocchi-with-brown-butter', source: 'ba', category: 'Italian' },
  { url: 'https://www.bonappetit.com/recipe/pesto-pasta', source: 'ba', category: 'Italian' },
  { url: 'https://www.bonappetit.com/recipe/eggplant-parmesan', source: 'ba', category: 'Italian' },
  { url: 'https://www.bonappetit.com/recipe/simple-marinara-sauce', source: 'ba', category: 'Italian' },
  { url: 'https://www.bonappetit.com/recipe/tiramisu', source: 'ba', category: 'Italian' },
  { url: 'https://www.bonappetit.com/recipe/panna-cotta', source: 'ba', category: 'Italian' },
  { url: 'https://www.bonappetit.com/recipe/aglio-e-olio', source: 'ba', category: 'Italian' },
  { url: 'https://www.bonappetit.com/recipe/bucatini-all-amatriciana', source: 'ba', category: 'Italian' },
  { url: 'https://www.bonappetit.com/recipe/baked-ziti', source: 'ba', category: 'Italian' },
  { url: 'https://www.bonappetit.com/recipe/pasta-puttanesca', source: 'ba', category: 'Italian' },
  { url: 'https://www.bonappetit.com/recipe/chicken-piccata', source: 'ba', category: 'Italian' },
  { url: 'https://www.bonappetit.com/recipe/osso-buco', source: 'ba', category: 'Italian' },
  { url: 'https://www.bonappetit.com/recipe/italian-wedding-soup', source: 'ba', category: 'Italian' },
  { url: 'https://www.bonappetit.com/recipe/caprese-salad', source: 'ba', category: 'Italian' },
  { url: 'https://www.bonappetit.com/recipe/bruschetta', source: 'ba', category: 'Italian' },
  { url: 'https://www.bonappetit.com/recipe/classic-meatballs', source: 'ba', category: 'Italian' },
  { url: 'https://www.bonappetit.com/recipe/pasta-e-fagioli', source: 'ba', category: 'Italian' },
  { url: 'https://www.bonappetit.com/recipe/cannoli', source: 'ba', category: 'Italian' },
  { url: 'https://www.bonappetit.com/recipe/cioppino', source: 'ba', category: 'Italian' },
  { url: 'https://www.bonappetit.com/recipe/burrata-with-cherry-tomatoes', source: 'ba', category: 'Italian' },
  { url: 'https://www.bonappetit.com/recipe/veal-milanese', source: 'ba', category: 'Italian' },
  { url: 'https://www.bonappetit.com/recipe/minestrone-soup', source: 'ba', category: 'Italian' },

  // --- Asian (~30) ---
  { url: 'https://www.bonappetit.com/recipe/pad-thai', source: 'ba', category: 'Asian' },
  { url: 'https://www.bonappetit.com/recipe/kung-pao-chicken', source: 'ba', category: 'Asian' },
  { url: 'https://www.bonappetit.com/recipe/best-fried-rice', source: 'ba', category: 'Asian' },
  { url: 'https://www.bonappetit.com/recipe/shoyu-ramen', source: 'ba', category: 'Asian' },
  { url: 'https://www.bonappetit.com/recipe/pork-dumplings', source: 'ba', category: 'Asian' },
  { url: 'https://www.bonappetit.com/recipe/chicken-stir-fry', source: 'ba', category: 'Asian' },
  { url: 'https://www.bonappetit.com/recipe/teriyaki-chicken', source: 'ba', category: 'Asian' },
  { url: 'https://www.bonappetit.com/recipe/bibimbap', source: 'ba', category: 'Asian' },
  { url: 'https://www.bonappetit.com/recipe/beef-pho', source: 'ba', category: 'Asian' },
  { url: 'https://www.bonappetit.com/recipe/dan-dan-noodles', source: 'ba', category: 'Asian' },
  { url: 'https://www.bonappetit.com/recipe/mapo-tofu', source: 'ba', category: 'Asian' },
  { url: 'https://www.bonappetit.com/recipe/general-tsos-chicken', source: 'ba', category: 'Asian' },
  { url: 'https://www.bonappetit.com/recipe/orange-chicken', source: 'ba', category: 'Asian' },
  { url: 'https://www.bonappetit.com/recipe/cold-sesame-noodles', source: 'ba', category: 'Asian' },
  { url: 'https://www.bonappetit.com/recipe/thai-green-curry', source: 'ba', category: 'Asian' },
  { url: 'https://www.bonappetit.com/recipe/tonkatsu', source: 'ba', category: 'Asian' },
  { url: 'https://www.bonappetit.com/recipe/miso-soup', source: 'ba', category: 'Asian' },
  { url: 'https://www.bonappetit.com/recipe/japanese-curry', source: 'ba', category: 'Asian' },
  { url: 'https://www.bonappetit.com/recipe/scallion-pancakes', source: 'ba', category: 'Asian' },
  { url: 'https://www.bonappetit.com/recipe/char-siu-pork', source: 'ba', category: 'Asian' },
  { url: 'https://www.bonappetit.com/recipe/korean-fried-chicken', source: 'ba', category: 'Asian' },
  { url: 'https://www.bonappetit.com/recipe/tom-yum-soup', source: 'ba', category: 'Asian' },
  { url: 'https://www.bonappetit.com/recipe/fresh-spring-rolls', source: 'ba', category: 'Asian' },
  { url: 'https://www.bonappetit.com/recipe/lo-mein', source: 'ba', category: 'Asian' },
  { url: 'https://www.bonappetit.com/recipe/kimchi-jjigae', source: 'ba', category: 'Asian' },
  { url: 'https://www.bonappetit.com/recipe/thai-basil-chicken', source: 'ba', category: 'Asian' },
  { url: 'https://www.bonappetit.com/recipe/wonton-soup', source: 'ba', category: 'Asian' },
  { url: 'https://www.bonappetit.com/recipe/japchae', source: 'ba', category: 'Asian' },
  { url: 'https://www.bonappetit.com/recipe/katsu-curry', source: 'ba', category: 'Asian' },
  { url: 'https://www.bonappetit.com/recipe/sushi-rice', source: 'ba', category: 'Asian' },

  // --- Mexican/Latin (~20) ---
  { url: 'https://www.bonappetit.com/recipe/tacos-al-pastor', source: 'ba', category: 'Mexican' },
  { url: 'https://www.bonappetit.com/recipe/slow-roasted-pork-carnitas', source: 'ba', category: 'Mexican' },
  { url: 'https://www.bonappetit.com/recipe/chicken-enchiladas-verdes', source: 'ba', category: 'Mexican' },
  { url: 'https://www.bonappetit.com/recipe/perfect-guacamole', source: 'ba', category: 'Mexican' },
  { url: 'https://www.bonappetit.com/recipe/elote-mexican-street-corn', source: 'ba', category: 'Mexican' },
  { url: 'https://www.bonappetit.com/recipe/churros', source: 'ba', category: 'Mexican' },
  { url: 'https://www.bonappetit.com/recipe/black-beans-from-scratch', source: 'ba', category: 'Mexican' },
  { url: 'https://www.bonappetit.com/recipe/mexican-red-rice', source: 'ba', category: 'Mexican' },
  { url: 'https://www.bonappetit.com/recipe/birria-tacos', source: 'ba', category: 'Mexican' },
  { url: 'https://www.bonappetit.com/recipe/chiles-rellenos', source: 'ba', category: 'Mexican' },
  { url: 'https://www.bonappetit.com/recipe/pico-de-gallo', source: 'ba', category: 'Mexican' },
  { url: 'https://www.bonappetit.com/recipe/chicken-tortilla-soup', source: 'ba', category: 'Mexican' },
  { url: 'https://www.bonappetit.com/recipe/chilaquiles-rojos', source: 'ba', category: 'Mexican' },
  { url: 'https://www.bonappetit.com/recipe/pork-tamales', source: 'ba', category: 'Mexican' },
  { url: 'https://www.bonappetit.com/recipe/carne-asada', source: 'ba', category: 'Mexican' },
  { url: 'https://www.bonappetit.com/recipe/pozole-rojo', source: 'ba', category: 'Mexican' },
  { url: 'https://www.bonappetit.com/recipe/mole-poblano', source: 'ba', category: 'Mexican' },
  { url: 'https://www.bonappetit.com/recipe/refried-beans', source: 'ba', category: 'Mexican' },
  { url: 'https://www.bonappetit.com/recipe/chicken-quesadillas', source: 'ba', category: 'Mexican' },
  { url: 'https://www.bonappetit.com/recipe/beef-empanadas', source: 'ba', category: 'Mexican' },

  // --- Baking & Desserts (~40) ---
  { url: 'https://www.bonappetit.com/recipe/bas-best-banana-bread', source: 'ba', category: 'Baking' },
  { url: 'https://www.bonappetit.com/recipe/bas-best-chocolate-chip-cookies', source: 'ba', category: 'Baking' },
  { url: 'https://www.bonappetit.com/recipe/bas-best-brownies', source: 'ba', category: 'Baking' },
  { url: 'https://www.bonappetit.com/recipe/bas-best-chocolate-cake', source: 'ba', category: 'Baking' },
  { url: 'https://www.bonappetit.com/recipe/bas-best-apple-pie', source: 'ba', category: 'Baking' },
  { url: 'https://www.bonappetit.com/recipe/bas-best-cinnamon-rolls', source: 'ba', category: 'Baking' },
  { url: 'https://www.bonappetit.com/recipe/no-knead-bread', source: 'ba', category: 'Baking' },
  { url: 'https://www.bonappetit.com/recipe/bas-best-pizza-dough', source: 'ba', category: 'Baking' },
  { url: 'https://www.bonappetit.com/recipe/focaccia', source: 'ba', category: 'Baking' },
  { url: 'https://www.bonappetit.com/recipe/cream-scones', source: 'ba', category: 'Baking' },
  { url: 'https://www.bonappetit.com/recipe/all-butter-pie-crust', source: 'ba', category: 'Baking' },
  { url: 'https://www.bonappetit.com/recipe/new-york-cheesecake', source: 'ba', category: 'Baking' },
  { url: 'https://www.bonappetit.com/recipe/sugar-cookies', source: 'ba', category: 'Baking' },
  { url: 'https://www.bonappetit.com/recipe/blondies', source: 'ba', category: 'Baking' },
  { url: 'https://www.bonappetit.com/recipe/sourdough-bread', source: 'ba', category: 'Baking' },
  { url: 'https://www.bonappetit.com/recipe/lemon-bars', source: 'ba', category: 'Baking' },
  { url: 'https://www.bonappetit.com/recipe/carrot-cake-with-cream-cheese-frosting', source: 'ba', category: 'Baking' },
  { url: 'https://www.bonappetit.com/recipe/pumpkin-pie', source: 'ba', category: 'Baking' },
  { url: 'https://www.bonappetit.com/recipe/pecan-pie', source: 'ba', category: 'Baking' },
  { url: 'https://www.bonappetit.com/recipe/red-velvet-cake', source: 'ba', category: 'Baking' },
  { url: 'https://www.bonappetit.com/recipe/challah-bread', source: 'ba', category: 'Baking' },
  { url: 'https://www.bonappetit.com/recipe/homemade-croissants', source: 'ba', category: 'Baking' },
  { url: 'https://www.bonappetit.com/recipe/peanut-butter-cookies', source: 'ba', category: 'Baking' },
  { url: 'https://www.bonappetit.com/recipe/oatmeal-raisin-cookies', source: 'ba', category: 'Baking' },
  { url: 'https://www.bonappetit.com/recipe/snickerdoodles', source: 'ba', category: 'Baking' },
  { url: 'https://www.bonappetit.com/recipe/brioche', source: 'ba', category: 'Baking' },
  { url: 'https://www.bonappetit.com/recipe/classic-pound-cake', source: 'ba', category: 'Baking' },
  { url: 'https://www.bonappetit.com/recipe/blueberry-muffins', source: 'ba', category: 'Baking' },
  { url: 'https://www.bonappetit.com/recipe/strawberry-shortcake', source: 'ba', category: 'Baking' },
  { url: 'https://www.bonappetit.com/recipe/chocolate-mousse', source: 'ba', category: 'Baking' },
  { url: 'https://www.bonappetit.com/recipe/creme-brulee', source: 'ba', category: 'Baking' },
  { url: 'https://www.bonappetit.com/recipe/peach-cobbler', source: 'ba', category: 'Baking' },
  { url: 'https://www.bonappetit.com/recipe/key-lime-pie', source: 'ba', category: 'Baking' },
  { url: 'https://www.bonappetit.com/recipe/sticky-toffee-pudding', source: 'ba', category: 'Baking' },
  { url: 'https://www.bonappetit.com/recipe/chocolate-lava-cakes', source: 'ba', category: 'Baking' },
  { url: 'https://www.bonappetit.com/recipe/tres-leches-cake', source: 'ba', category: 'Baking' },
  { url: 'https://www.bonappetit.com/recipe/apple-crisp', source: 'ba', category: 'Baking' },
  { url: 'https://www.bonappetit.com/recipe/chocolate-babka', source: 'ba', category: 'Baking' },
  { url: 'https://www.bonappetit.com/recipe/double-chocolate-cookies', source: 'ba', category: 'Baking' },
  { url: 'https://www.bonappetit.com/recipe/lemon-poppy-seed-muffins', source: 'ba', category: 'Baking' },

  // --- Soups & Stews (~20) ---
  { url: 'https://www.bonappetit.com/recipe/chicken-noodle-soup', source: 'ba', category: 'Soup' },
  { url: 'https://www.bonappetit.com/recipe/creamy-tomato-soup', source: 'ba', category: 'Soup' },
  { url: 'https://www.bonappetit.com/recipe/french-onion-soup', source: 'ba', category: 'Soup' },
  { url: 'https://www.bonappetit.com/recipe/new-england-clam-chowder', source: 'ba', category: 'Soup' },
  { url: 'https://www.bonappetit.com/recipe/classic-beef-stew', source: 'ba', category: 'Soup' },
  { url: 'https://www.bonappetit.com/recipe/red-lentil-soup', source: 'ba', category: 'Soup' },
  { url: 'https://www.bonappetit.com/recipe/split-pea-soup', source: 'ba', category: 'Soup' },
  { url: 'https://www.bonappetit.com/recipe/butternut-squash-soup', source: 'ba', category: 'Soup' },
  { url: 'https://www.bonappetit.com/recipe/corn-chowder', source: 'ba', category: 'Soup' },
  { url: 'https://www.bonappetit.com/recipe/chicken-and-rice-soup', source: 'ba', category: 'Soup' },
  { url: 'https://www.bonappetit.com/recipe/tortellini-en-brodo', source: 'ba', category: 'Soup' },
  { url: 'https://www.bonappetit.com/recipe/gazpacho', source: 'ba', category: 'Soup' },
  { url: 'https://www.bonappetit.com/recipe/tuscan-white-bean-soup', source: 'ba', category: 'Soup' },
  { url: 'https://www.bonappetit.com/recipe/broccoli-cheddar-soup', source: 'ba', category: 'Soup' },
  { url: 'https://www.bonappetit.com/recipe/mushroom-barley-soup', source: 'ba', category: 'Soup' },
  { url: 'https://www.bonappetit.com/recipe/potato-leek-soup', source: 'ba', category: 'Soup' },
  { url: 'https://www.bonappetit.com/recipe/matzo-ball-soup', source: 'ba', category: 'Soup' },
  { url: 'https://www.bonappetit.com/recipe/black-bean-soup', source: 'ba', category: 'Soup' },
  { url: 'https://www.bonappetit.com/recipe/ribollita', source: 'ba', category: 'Soup' },
  { url: 'https://www.bonappetit.com/recipe/white-chicken-chili', source: 'ba', category: 'Soup' },

  // --- Breakfast (~20) ---
  { url: 'https://www.bonappetit.com/recipe/bas-best-pancakes', source: 'ba', category: 'Breakfast' },
  { url: 'https://www.bonappetit.com/recipe/french-toast', source: 'ba', category: 'Breakfast' },
  { url: 'https://www.bonappetit.com/recipe/perfect-scrambled-eggs', source: 'ba', category: 'Breakfast' },
  { url: 'https://www.bonappetit.com/recipe/eggs-benedict', source: 'ba', category: 'Breakfast' },
  { url: 'https://www.bonappetit.com/recipe/homemade-granola', source: 'ba', category: 'Breakfast' },
  { url: 'https://www.bonappetit.com/recipe/overnight-oats', source: 'ba', category: 'Breakfast' },
  { url: 'https://www.bonappetit.com/recipe/vegetable-frittata', source: 'ba', category: 'Breakfast' },
  { url: 'https://www.bonappetit.com/recipe/quiche-lorraine', source: 'ba', category: 'Breakfast' },
  { url: 'https://www.bonappetit.com/recipe/bas-best-waffles', source: 'ba', category: 'Breakfast' },
  { url: 'https://www.bonappetit.com/recipe/shakshuka', source: 'ba', category: 'Breakfast' },
  { url: 'https://www.bonappetit.com/recipe/breakfast-burritos', source: 'ba', category: 'Breakfast' },
  { url: 'https://www.bonappetit.com/recipe/avocado-toast', source: 'ba', category: 'Breakfast' },
  { url: 'https://www.bonappetit.com/recipe/dutch-baby', source: 'ba', category: 'Breakfast' },
  { url: 'https://www.bonappetit.com/recipe/crepes', source: 'ba', category: 'Breakfast' },
  { url: 'https://www.bonappetit.com/recipe/egg-in-a-hole', source: 'ba', category: 'Breakfast' },
  { url: 'https://www.bonappetit.com/recipe/breakfast-hash', source: 'ba', category: 'Breakfast' },
  { url: 'https://www.bonappetit.com/recipe/chia-pudding', source: 'ba', category: 'Breakfast' },
  { url: 'https://www.bonappetit.com/recipe/steel-cut-oatmeal', source: 'ba', category: 'Breakfast' },
  { url: 'https://www.bonappetit.com/recipe/huevos-rancheros', source: 'ba', category: 'Breakfast' },
  { url: 'https://www.bonappetit.com/recipe/breakfast-strata', source: 'ba', category: 'Breakfast' },

  // --- Salads & Sides (~20) ---
  { url: 'https://www.bonappetit.com/recipe/classic-caesar-salad', source: 'ba', category: 'Salad' },
  { url: 'https://www.bonappetit.com/recipe/greek-salad', source: 'ba', category: 'Salad' },
  { url: 'https://www.bonappetit.com/recipe/roasted-vegetables', source: 'ba', category: 'Salad' },
  { url: 'https://www.bonappetit.com/recipe/potato-gratin', source: 'ba', category: 'Salad' },
  { url: 'https://www.bonappetit.com/recipe/green-beans-almondine', source: 'ba', category: 'Salad' },
  { url: 'https://www.bonappetit.com/recipe/roasted-brussels-sprouts', source: 'ba', category: 'Salad' },
  { url: 'https://www.bonappetit.com/recipe/roasted-sweet-potatoes', source: 'ba', category: 'Salad' },
  { url: 'https://www.bonappetit.com/recipe/cobb-salad', source: 'ba', category: 'Salad' },
  { url: 'https://www.bonappetit.com/recipe/wedge-salad', source: 'ba', category: 'Salad' },
  { url: 'https://www.bonappetit.com/recipe/creamed-spinach', source: 'ba', category: 'Salad' },
  { url: 'https://www.bonappetit.com/recipe/glazed-carrots', source: 'ba', category: 'Salad' },
  { url: 'https://www.bonappetit.com/recipe/waldorf-salad', source: 'ba', category: 'Salad' },
  { url: 'https://www.bonappetit.com/recipe/fattoush', source: 'ba', category: 'Salad' },
  { url: 'https://www.bonappetit.com/recipe/hasselback-potatoes', source: 'ba', category: 'Salad' },
  { url: 'https://www.bonappetit.com/recipe/sauteed-mushrooms', source: 'ba', category: 'Salad' },
  { url: 'https://www.bonappetit.com/recipe/grilled-corn-on-the-cob', source: 'ba', category: 'Salad' },
  { url: 'https://www.bonappetit.com/recipe/tabbouleh', source: 'ba', category: 'Salad' },
  { url: 'https://www.bonappetit.com/recipe/kale-salad-with-apple', source: 'ba', category: 'Salad' },
  { url: 'https://www.bonappetit.com/recipe/roasted-cauliflower', source: 'ba', category: 'Salad' },
  { url: 'https://www.bonappetit.com/recipe/panzanella', source: 'ba', category: 'Salad' },

  // --- Seafood (~15) ---
  { url: 'https://www.bonappetit.com/recipe/slow-roasted-salmon', source: 'ba', category: 'Seafood' },
  { url: 'https://www.bonappetit.com/recipe/honey-garlic-salmon', source: 'ba', category: 'Seafood' },
  { url: 'https://www.bonappetit.com/recipe/shrimp-scampi', source: 'ba', category: 'Seafood' },
  { url: 'https://www.bonappetit.com/recipe/fish-tacos-with-slaw', source: 'ba', category: 'Seafood' },
  { url: 'https://www.bonappetit.com/recipe/maryland-crab-cakes', source: 'ba', category: 'Seafood' },
  { url: 'https://www.bonappetit.com/recipe/steamed-lobster-with-drawn-butter', source: 'ba', category: 'Seafood' },
  { url: 'https://www.bonappetit.com/recipe/mussels-in-white-wine', source: 'ba', category: 'Seafood' },
  { url: 'https://www.bonappetit.com/recipe/seared-scallops', source: 'ba', category: 'Seafood' },
  { url: 'https://www.bonappetit.com/recipe/pan-roasted-halibut', source: 'ba', category: 'Seafood' },
  { url: 'https://www.bonappetit.com/recipe/grilled-swordfish', source: 'ba', category: 'Seafood' },
  { url: 'https://www.bonappetit.com/recipe/coconut-shrimp', source: 'ba', category: 'Seafood' },
  { url: 'https://www.bonappetit.com/recipe/blackened-fish', source: 'ba', category: 'Seafood' },
  { url: 'https://www.bonappetit.com/recipe/tuna-poke-bowl', source: 'ba', category: 'Seafood' },
  { url: 'https://www.bonappetit.com/recipe/fish-and-chips', source: 'ba', category: 'Seafood' },
  { url: 'https://www.bonappetit.com/recipe/lemon-butter-cod', source: 'ba', category: 'Seafood' },

  // --- Indian/Middle Eastern (~15) ---
  { url: 'https://www.bonappetit.com/recipe/butter-chicken', source: 'ba', category: 'Indian' },
  { url: 'https://www.bonappetit.com/recipe/chicken-tikka-masala', source: 'ba', category: 'Indian' },
  { url: 'https://www.bonappetit.com/recipe/red-lentil-dal', source: 'ba', category: 'Indian' },
  { url: 'https://www.bonappetit.com/recipe/best-hummus', source: 'ba', category: 'Indian' },
  { url: 'https://www.bonappetit.com/recipe/crispy-falafel', source: 'ba', category: 'Indian' },
  { url: 'https://www.bonappetit.com/recipe/chicken-shawarma', source: 'ba', category: 'Indian' },
  { url: 'https://www.bonappetit.com/recipe/chicken-biryani', source: 'ba', category: 'Indian' },
  { url: 'https://www.bonappetit.com/recipe/homemade-naan', source: 'ba', category: 'Indian' },
  { url: 'https://www.bonappetit.com/recipe/chana-masala', source: 'ba', category: 'Indian' },
  { url: 'https://www.bonappetit.com/recipe/palak-paneer', source: 'ba', category: 'Indian' },
  { url: 'https://www.bonappetit.com/recipe/baba-ganoush', source: 'ba', category: 'Indian' },
  { url: 'https://www.bonappetit.com/recipe/lamb-kofta', source: 'ba', category: 'Indian' },
  { url: 'https://www.bonappetit.com/recipe/vegetable-samosas', source: 'ba', category: 'Indian' },
  { url: 'https://www.bonappetit.com/recipe/tandoori-chicken', source: 'ba', category: 'Indian' },
  { url: 'https://www.bonappetit.com/recipe/grilled-lamb-kebabs', source: 'ba', category: 'Indian' },

  // ============================================================
  // RECDEX ORIGINALS — Quick Weeknight Dinners (Batch 1, 2026-03-25)
  // Synthesized from multiple curated sources, rewritten in RecDex voice
  // ============================================================
  { url: 'recdex://sheet-pan-chicken-thighs-with-roasted-vegetables', source: 'recdex', category: 'Weeknight' },
  { url: 'recdex://one-pot-creamy-tuscan-chicken', source: 'recdex', category: 'Weeknight' },
  { url: 'recdex://miso-butter-mushroom-pasta', source: 'recdex', category: 'Weeknight' },
  { url: 'recdex://skillet-chicken-with-lemon-and-olives', source: 'recdex', category: 'Weeknight' },
  { url: 'recdex://honey-soy-glazed-pork-chops', source: 'recdex', category: 'Weeknight' },
  { url: 'recdex://coconut-red-curry-lentils', source: 'recdex', category: 'Weeknight' },
  { url: 'recdex://seared-steak-with-chimichurri', source: 'recdex', category: 'Weeknight' },
  { url: 'recdex://one-pan-orzo-with-shrimp-and-feta', source: 'recdex', category: 'Weeknight' },
  { url: 'recdex://chicken-lettuce-wraps', source: 'recdex', category: 'Weeknight' },
  { url: 'recdex://sausage-and-white-bean-skillet', source: 'recdex', category: 'Weeknight' },
]
